//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginlogout
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRODUCTEntities : DbContext
    {
        public PRODUCTEntities()
            : base("name=PRODUCTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRODUCT_TABLE> PRODUCT_TABLE { get; set; }
        public virtual DbSet<Regi> Regi { get; set; }

        public System.Data.Entity.DbSet<loginlogout.Models.Membeship> Membeships { get; set; }
    }
}
