using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Id { get; set; }
        
        [Required(ErrorMessage ="this is required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "this is required")]

        public string LastName { get; set; }

        [Required(ErrorMessage = "this is required")]

        public System.DateTime Dob { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string Gender { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string EmpType { get; set; }
        [Required(ErrorMessage = "this is required")]

        public int Sal { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string Detp { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string Email { get; set; }

    }
  
}
