//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        public string Position { get; set; }
        [Required]

        public Nullable<int> Age { get; set; }
        [Required]

        public Nullable<int> Salary { get; set; }
    }
}
